# Dependencies
markdown:      redcarpet
highlighter:   true

# Permalinks
permalink:        pretty

# Setup
title:            Chris Holden
tagline:          'Remote sensing, Python, Science'
url:              https://ceholden.github.io/
baseurl:          /
paginate:         5
author:
  name:           Chris Holden
  url:            https://ceholden.github.io/
  email:          ceholden@gmail.com

disqus_shortname: ceholden

# FROM https://github.com/joshualande/joshualande.github.io
# This is the list of pages to include in the header of the website.
pages_list:
  About: '/about/'
  Utilities: '/repos/'
  Tags: '/tags/'

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ceholden/ceholden.github.io

gems:
  - jekyll-mentions
