# Dependencies
markdown:      redcarpet
highlighter:   true

# Permalinks
permalink:        pretty

# Exclude present folder since we'll make HTMLs ourself
exclude:          ['present/tips/*.md']

# Setup
title:            Chris Holden
tagline:          'Remote sensing, Python, Science'
url:              https://ceholden.github.io/
baseurl:          /
paginate:         5
author:
  name:           Chris Holden
  url:            https://ceholden.github.io/

disqus_shortname: ceholden

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/ceholden/ceholden.github.io

gems:
  - jekyll-mentions
  - github-pages
